### ISSUE TITLE
Sound distortions / Misc

### ISSUE THREAD

**Issue by Toy203** [gpstar81/GPStar-proton-pack#266]
I got some weird distorsions with the gpboard on 1984/89 sounds bite for boot and shutdown. I've turned down my ampli for the second test and removed one of the two speaker since i dented it so i though that might be the cause, but still i can hear the distortions. 

https://youtube.com/shorts/Vh1qnQuZVUA?feature=share
https://youtube.com/shorts/p3-mllN5vno?feature=share
https://youtube.com/shorts/LBDQtEsEe8E

I can hear a hiss when music track starts playing:
https://youtube.com/shorts/d2VHScUqNOk

All this could be due the new default board amplification. 

Also it feels like the board anticipates a few millisecs the sounds rather than the wand trigger. See here, i was manually starting and stopping the music play from the ESP menu, you can hear the wand piano starts a bit early.
https://youtu.be/VgiZF7HABHo

As of now, i can hear volume changing beep while using the crank with the pack idling, but no beeps are played once it is in the On mode. Volume still goes up and down as expected even without hearing the beeps.

**Comment by nomakewan** [comment]
So, a few questions if you don't mind.

1. Do you have a ground loop isolator between the WAV Trigger output and the speaker amplifier? Not having one can cause distortion to appear in the output audio.
2. The video link to "I can hear a hiss when music track starts playing" leads to a "This video isn't available anymore" page.

A lack of ground loop isolator can be the cause for the distortion effects seen in the first, second, and fifth videos you linked. The distortion in the third video you linked is actually in the audio file itself, which you can hear here: [Shutdown Sound](https://github.com/gpstar81/GPStar-proton-pack/raw/main/sounds/002_shutdown.wav)

Fixing that distortion should be easy but I'll have to ask the other devs if it was in the sound file intentionally since it's been like that for well over a year.

**Comment by Toy203** [comment]
Sorry i forgot to mention, yes this is with ground loop isolator installed. I'm testing the GPstar audio board atm so i figured the default amplification might be a bit high.

Here's the hiss video link again
https://youtube.com/shorts/d2VHScUqNOk

Thanks for letting me know that weird wishy washy sound it's in the file though, i never noticed. So weird!

The fifth video was just to remark it feels like the pack and the wand aren't perfectly synched up with audio in my case. Maybe it's just me though. I'm becoming Lord Nitpick.

**Comment by nomakewan** [comment]
Ah, I wasn't aware you were testing the GPStar board! In that case this could indeed be related to that code branch, my apologies. Thank you very much for being a beta tester! And yes, that video link now works.

Hey, being Lord Nitpick is awesome, because it makes the kit that much better for everyone when these sorts of things get found and fixed.

**Comment by gpstar81** [comment]
Thanks for the wand sound timing video. That confirms my suspicions on a few things where I need to fix up a bit more which may solve a few other small timing issues that we discussed earlier.

Could you also point out what the volume levels are on both the pack crank knob and the amp, to give me a idea on a few other things.

Thanks.

**Comment by Toy203** [comment]
> Could you also point out what the volume levels are on both the pack crank knob and the amp, to give me a idea on a few other things.
Not sure i get this. I keep my amp knob on half way through. Pack don't have a fixed setting i tried it at max and lowered it to make some videos.

**Comment by nomakewan** [comment]
Just a quick mention that the latest updates to the Audio WIP branch includes a new shutdown sound to remove the distortion heard there. Thank you for your report!
