### ISSUE TITLE
Power intensityis backwards [Bug]: <short description>

### ISSUE THREAD

**Issue by Cevans9820** [gpstar81/GPStar-proton-pack#339]
### What actions were attempted?

I turned on my pack in 89 mode, ans increase the power level on my wand and when I did the power level is backwards, when I fire on level 5 it fires like it's on level one and vice versa.

### What actually happened?

When I move the wand to level 5 to overheat the wand it fired like it was in level 1 

### What was expected?

I wasn't expecting the power levels to be backwards

### Firmware Version

5.3.1

### Mode in Use

Super Hero / Video Game

### Notable Hardware

N/a

### Homework Completed

- [X] I did my part!

**Comment by nomakewan** [comment]
If you are referring to the color scheme of the proton stream, that is actually completely intentional.

Here is the team firing their Proton Packs indoors:
![Ghostbusters II (1989) (2160p BluRay x265 10bit HDR Tigole) mkv_snapshot_00 34 55 601](https://github.com/gpstar81/GPStar-proton-pack/assets/11485516/b4f74649-d50c-443f-9909-6e4be4b6716e)

And here is what it looked like after Egon told everyone, "Full Neutronas":
![Ghostbusters II (1989) (2160p BluRay x265 10bit HDR Tigole) mkv_snapshot_01 25 01 301](https://github.com/gpstar81/GPStar-proton-pack/assets/11485516/8fc887e1-2481-4b57-8700-38ce3568bda2)

Which is why in the changelog for 5.3.0 you will find the line:
`-1989 proton stream sounds and colors updated to match film`

Is this indeed what you are referring to?

**Comment by Cevans9820** [comment]
Ahhhhh gotcha

**Comment by nomakewan** [comment]
Since that seems like what this issue is referring to, I'll be closing it. Feel free to reopen it if you feel there is another bug relating to wand power level in 1989 year mode.
